### PR TITLE
Included BRANCHID node

### PR DESCRIPTION
**Pull request by ricardovicente**
Included the item agencyNumber referring to BRANCHID node in the method buildBankAccount

### CODE REVIEW

**Comment by asgrim** [comment]
Is BRANCHID always present?

**Comment by ricardovicente** [comment]
Yes, at least in banks operating in Brazil, is no such requirement.
Always!

**Comment by asgrim** [comment]
Thanks! :)

**Comment by asgrim** [comment]
This is included in 1.0.2

**Pull request merged**
