### PR TITLE
Replace "&" sign in XML tag value by its html code

### LINKED ISSUE #53: xmlParseEntityRef: no name
I am getting the following error "**xmlParseEntityRef: no name**" when trying to parse an ofx file submitted from a file upload form.

I searched over the internet and it looks like the problem is related to the stray ‘&’ (ampersand character) somewhere in the file. How can I come over this? They suggest to remove or encode the ampersand, but the file is being uploaded from an upload form.

```
$file_path = $_FILES["fileUpload"]["tmp_name"];

$ofxParser = new \OfxParser\Parser();
$ofx = $ofxParser->loadFromFile($file_path);

$bankAccount = reset($ofx->bankAccounts);

// Get the statement transactions for the account
$transactions = $bankAccount->statement->transactions;

var_dump($startDate, $endDate, $transactions);


```

### PR DESCRIPTION
**Pull request by nicolasrabier**
In OFX files, some tag values like in MEMO tag contains special characters such as the '&' sign which generate an issue with simplexml_load_string function. 

`LibXMLError::__set_state(array(      'level' => 3,      'code' => 68,      'column' => 30,      'message' => 'xmlParseEntityRef: no name ',      'file' => '',      'line' => 27,   )),`

This code simply converts the '&' sign to its html code (&amp;) which is tolerated by simplexml_load_string.

Fixes #53

### CODE REVIEW

**Comment by asgrim** [comment]
@nicolasrabier for this test, it's probably going to make sense to add another test case into the `convertSgmlToXmlProvivder()`:

https://github.com/asgrim/ofxparser/blob/93ddca0acc2bf0a688f1f98a5f122048e6cbd832/tests/OfxParser/ParserTest.php#L85-L129

The alignment is really wonky there I noticed too :laughing:

**Comment by asgrim** [comment]
May also make sense to add a fixture with a functional tests too

**Comment by asgrim** [comment]
Thanks @nicolasrabier !

**Comment by nicolasrabier** [comment]
> Thanks @nicolasrabier !

No worries!

**Pull request merged**
