### PR TITLE
Fix file parser

### PR DESCRIPTION
**Pull request by otaavioo**
#20 Support multi-line and one-line OFX

### CODE REVIEW

**Comment by ambroisemaupate** [comment]
Be careful @otaavioo, your PR does not fix issues with one-line OFX files. (eg. https://github.com/ambroisemaupate/ofxparser/blob/fix/tests/fixtures/ofxdata-oneline.ofx)

See my fork to use PHPUnit tests with some French banks OFX samples.

https://github.com/ambroisemaupate/ofxparser/tree/fix

**Comment by asgrim** [comment]
Umm, not merging this as you're trying to change the package name... See comment from @ambroisemaupate

**Comment by asgrim** [comment]
@otaavioo @agenciasys the single/multi-line issue should be fixed in release 1.2.0, just released, let me know if you get any issues! Thanks :)

**Comment by otaavioo** [comment]
Thank you man!

**Pull request closed without merging**
